import { Router } from 'express';
import EditTodoRouter from './editTodo.js';import EditFinancialStatementRouter from './editFinancialStatement.js';import EditBalanceSheetRouter from './editBalanceSheet.js';import EditIncomeStatementRouter from './editIncomeStatement.js';import EditCashflowStatementRouter from './editCashflowStatement.js';import EditFaTransactionRouter from './editFaTransaction.js';import EditFixedAssetsRouter from './editFixedAssets.js';import EditAccountRouter from './editAccount.js';import EditJournalRouter from './editJournal.js';import EditAlarmRouter from './editAlarm.js';import EditUserRouter from './editUser.js';import EditDepartmentRouter from './editDepartment.js';import EditEmployeeRouter from './editEmployee.js';import EditCustomerRouter from './editCustomer.js';import EditBankRouter from './editBank.js';import EditLoanRouter from './editLoan.js';import EditCashflowRouter from './editCashflow.js';import EditCompanyRouter from './editCompany.js';import EditProductRouter from './editProduct.js';import EditInvRouter from './editInv.js';import EditVendorRouter from './editVendor.js';import EditPaymentMethodRouter from './editPaymentMethod.js';import EditPettyCashRouter from './editPettyCash.js';import EditPoReceivedRouter from './editPoReceived.js';import EditSoReceivableRouter from './editSoReceivable.js';import EditReturnsAndAllowancesRouter from './editReturnsAndAllowances.js';import EditProjectRouter from './editProject.js';import EditSalariesRouter from './editSalaries.js';import EditShopRouter from './editShop.js';import EditStorageRouter from './editStorage.js';import EditBusiness_unitRouter from './editBusiness_unit.js';import EditExpenseRouter from './editExpense.js';import EditSalesTargetRouter from './editSalesTarget.js';import EditPoForecastRouter from './editPoForecast.js';import EditInsuranceRouter from './editInsurance.js';import EditUploadRouter from './editUpload.js';
const EditRouter = Router();

/**
 * 所有表的 RestAPI 設計
 * POST     /table      新增資料
 * GET      /table      取得所有資料
 * PUT      /table/:id  取得一筆資料
 * PUT      /table/:id  更新資料
 * DELETE   /table/:id  刪除資料
 **/

EditRouter.use('/todo', EditTodoRouter);EditRouter.use('/financialStatement', EditFinancialStatementRouter);EditRouter.use('/balanceSheet', EditBalanceSheetRouter);EditRouter.use('/incomeStatement', EditIncomeStatementRouter);EditRouter.use('/cashflowStatement', EditCashflowStatementRouter);EditRouter.use('/faTransaction', EditFaTransactionRouter);EditRouter.use('/fixedAssets', EditFixedAssetsRouter);EditRouter.use('/account', EditAccountRouter);EditRouter.use('/journal', EditJournalRouter);EditRouter.use('/alarm', EditAlarmRouter);EditRouter.use('/user', EditUserRouter);EditRouter.use('/department', EditDepartmentRouter);EditRouter.use('/employee', EditEmployeeRouter);EditRouter.use('/customer', EditCustomerRouter);EditRouter.use('/bank', EditBankRouter);EditRouter.use('/loan', EditLoanRouter);EditRouter.use('/cashflow', EditCashflowRouter);EditRouter.use('/company', EditCompanyRouter);EditRouter.use('/product', EditProductRouter);EditRouter.use('/inv', EditInvRouter);EditRouter.use('/vendor', EditVendorRouter);EditRouter.use('/paymentMethod', EditPaymentMethodRouter);EditRouter.use('/pettyCash', EditPettyCashRouter);EditRouter.use('/poReceived', EditPoReceivedRouter);EditRouter.use('/soReceivable', EditSoReceivableRouter);EditRouter.use('/returnsAndAllowances', EditReturnsAndAllowancesRouter);EditRouter.use('/project', EditProjectRouter);EditRouter.use('/salaries', EditSalariesRouter);EditRouter.use('/shop', EditShopRouter);EditRouter.use('/storage', EditStorageRouter);EditRouter.use('/business_unit', EditBusiness_unitRouter);EditRouter.use('/expense', EditExpenseRouter);EditRouter.use('/salesTarget', EditSalesTargetRouter);EditRouter.use('/poForecast', EditPoForecastRouter);EditRouter.use('/insurance', EditInsuranceRouter);EditRouter.use('/upload', EditUploadRouter);

export default EditRouter;